### PR TITLE
Make the package installable.

### PR DESCRIPTION
**Pull request by marfvr**
This PR aims to make the `inferrer` package an installable package.

After the merge, it can be installed with:
```
pip install git+https://github.com/steynvl/inferrer.git
```

Or:
```
pipenv install git+https://github.com/steynvl/inferrer.git#egg=inferrer
```

It's great work! You should consider publishing the package on PyPI.

### CODE REVIEW

**Comment by steynvl** [comment]
Hi Marco, thank you very much, appreciate it. Good luck with the work; let me know if you have any questions.

**Comment by steynvl** [comment]
I was under the impression that it would only merge in the setup.py file to make the package installable, but it seems that your later commits also got merged in. I think I'm fine with it, but let me know if you think I should rather rebase and just add the setup file.

**Comment by marfvr** [comment]
Ops, my bad. I would keep the new feature outside the PR, so I'd proceed with the rebase.

Sorry for the inconvenience. 
If you are interested in that feature (that is, make the package work also with symbols with more than one character) we can discuss the details in another PR so to make the new feature more stable.

**Comment by steynvl** [comment]
Thanks, reverted the code. From your commits it seems like you are going the symbolic automata direction and learning example strings with separators. Feel free to send me an email (steyn.van.l@gmail.com) if you would like to discuss some stuff. And if the feature is stable, I would gladly merge it into master.

**Pull request merged**
